# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:radio-aktywne/template-package-python
accountname: radio-aktywne
description: Queueing utilities package for Python 🐍
docs: true
docsurl: https://radio-aktywne.github.io/pyqueues
importname: pyqueues
packagename: pyqueues
releases: true
reponame: pyqueues
repourl: https://github.com/radio-aktywne/pyqueues
